CREATE TABLE `CustomerService`.`InformalEmployee`( 
   `SerialNumber` VARCHAR(36) COMMENT '序号', 
   `EmployeeName` VARCHAR(36) COMMENT '员工姓名', 
   `Division` VARCHAR(36) COMMENT '事业部', 
   `UnderDivision` VARCHAR(36) COMMENT '事业部下一级组织', 
   `Project` VARCHAR(36) COMMENT '项目', 
   `PrimaryForms` VARCHAR(36) COMMENT '一级业态', 
   `JobCategory` VARCHAR(36) COMMENT '岗位类别', 
   `FirJobCategory` VARCHAR(36) COMMENT '一级岗位类别', 
   `SecJobCategory` VARCHAR(36) COMMENT '二级岗位类别', 
   `MainResponsibility` VARCHAR(36) COMMENT '三级岗位类别（第一主责）', 
   `Department` VARCHAR(36) COMMENT '部门', 
   `Position` VARCHAR(36) COMMENT '职务', 
   `Rank` VARCHAR(36) COMMENT '职级', 
   `Gender` VARCHAR(36) COMMENT '性别', 
   `IDCardNumber` VARCHAR(36) COMMENT '身份证号码', 
   `BirthDate` DATE COMMENT '出生日期', 
   `EntryTime` DATE COMMENT '入职时间', 
   `PositiveDate` DATE COMMENT '转正日期', 
   `WorkStartTime` DATE COMMENT '参加工作时间', 
   `IndustryStartTime` DATE COMMENT '行业从业起始时间', 
   `HighestDegree` VARCHAR(36) COMMENT '最高学历', 
   `GraduateSchool` VARCHAR(36) COMMENT '毕业院校', 
   `Major` VARCHAR(36) COMMENT '专业', 
   `PoliticalStatus` VARCHAR(36) COMMENT '政治面貌', 
   `Nation` VARCHAR(36) COMMENT '民族', 
   `ContractSigningUnit` VARCHAR(50) COMMENT '劳动合同签署单位', 
   `FirstSignTime` DATE COMMENT '首签劳动合同时间', 
   `ThisSignTime` DATE COMMENT '本次签订时间', 
   `ContractExpiresTime` DATE COMMENT '本次合同到期时间', 
   `NativePlace` VARCHAR(50) COMMENT '籍贯', 
   `ArchiveType` VARCHAR(50) COMMENT '存档类型', 
   `ArchivalPlace` VARCHAR(100) COMMENT '档案存放地', 
   `AccountType` VARCHAR(36) COMMENT '户口类型', 
   `CurrentAddress` VARCHAR(100) COMMENT '现住址', 
   `WorkingPlace` VARCHAR(100) COMMENT '工作地点',
   `year` INT COMMENT '加载数据年份',
   `month` INT COMMENT '加载数据月份'
 )
 
 
    `DomainAccount` VARCHAR(36) COMMENT '域账号', 
   `WorkingNature` VARCHAR(36) COMMENT '用工性质',